---
- name: test
  hosts: openstack_controller
  vars: 
    - SSL_cert_path: /home/ansible/Desktop/DOAN/ApacheHTTP_secure/files/SSL_cert
  tasks:
    - name: copy SSL cert
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/control/SSL 
      with_fileglob: 
        - "{{ SSL_cert_path }}/*"
      become: true
 


