---
- name: test
  hosts: localhost
  # become: yes
  vars:
    mysql_datadir: /var/lib/mysql
    mysql_slow_query_log_file: /var/log/mysql-slow.log
    mysql_owner: mysql
    mysql_group: mysql
    log_bin_basename: /var/lib/mysql/
    error_log_dir_file: /var/log/mysql/error.log
    relay_log_dir_file: /var/lib/mysql/ubuntu-relay-bin
    general_log_file: /var/lib/mysql/ubuntu.log
    plugin_dir: /usr/lib/mysql/plugin/
    secure_file_priv: /var/lib/mysql-files/
  tasks:
    - name: include file
      ansible.builtin.include_vars: 
        /home/hung/Desktop/DOAN/mysql_credential.yml
      
    - name: test  
      


        

