---
- name: test
  hosts: localhost
  # become: yes
  vars:
    keystone_path: /etc/keystone
    keystone_config_src: /home/ansible/Desktop/DOAN/openstack-security-checklist/templates/keystone.conf.j2
    keystone_config_dest: /etc/keystone/keystone.conf

    horizon_src: openstack-checklist/templates/local_settings.py.j2
    horizon_dest: /opt/stack/horizon/openstack_dashboard/local/local_settings.py
    #horizon_dest: /etc/openstack-dashboard/local_settings.py
    dashboard_conf: /home/ansible/Desktop/DOAN/openstack-checklist/templates/horizon.conf.j2
    dashboard_conf_apache: /etc/apache2/sites-available/horizon.conf

    nova_path: /etc/nova
    nova_src: /home/ansible/Desktop/DOAN/openstack-security-checklist/templates/nova.conf.j2
    nova_dest: /etc/nova/nova.conf

    cinder_path: /etc/cinder
    cinder_src: /home/ansible/Desktop/DOAN/openstack-security-checklist/templates/cinder.conf.j2
    cinder_dest: /etc/cinder/cinder.conf

    neutron_path: /etc/neutron
    neutron_src: /home/ansible/Desktop/DOAN/openstack-security-checklist/templates/neutron.conf.j2
    neutron_dest: /etc/neutron/neutron.conf
    splunk_version: 9.0.4.1
    splunk_tgz: splunk-9.0.4.1-419ad9369127-Linux-x86_64.tgz
    splunk_tgz_checksum: 41ece26237995aa9a9e9030a1ceed250
    SSL_cert_path: /home/ansible/Desktop/DOAN/ApacheHTTP_secure/templates/SSL_cert
  tasks:
    # - name: include file
    #   ansible.builtin.include_vars: 
    #     /home/ansible/Desktop/DOAN/mysql_credential.yml

    - name: Download by wget {{ splunk_tgz }}
      ansible.builtin.get_url:
        url: "https://download.splunk.com/products/splunk/releases/{{ splunk_version }}/linux/{{ splunk_tgz }}"
        checksum: "md5:{{ splunk_tgz_checksum }}"
        dest: /home/ansible
        mode: '0640'  
        owner: root
        group: root
      become: true
 


