---
- name: test
  hosts: localhost
  # become: yes
  vars:
    mysql_datadir: /var/lib/mysql
    mysql_slow_query_log_file: /var/log/mysql-slow.log
    mysql_owner: mysql
    mysql_group: mysql
    log_bin_basename: /var/lib/mysql/
    error_log_dir_file: /var/log/mysql/error.log
    relay_log_dir_file: /var/lib/mysql/ubuntu-relay-bin
    general_log_file: /var/lib/mysql/ubuntu.log
    plugin_dir: /usr/lib/mysql/plugin/
    secure_file_priv: /var/lib/mysql-files/
    
    openstack_file_owner: hung  ##change if needed
    openstack_file_group: hung 

    keystone_path: /etc/keystone
    horizon_path: /etc/openstack-dashboard/local_settings.py
    nova_path: /etc/nova
    cinder_path: /etc/cinder
    manila_path: /etc/manila
    neutron_path: /etc/neutron
    cron_tab_path: /etc
    cron_files_name: [cron.daily, cron.hourly, cron.monthly, cron.weekly, crontab]
    site_default_path: /etc/apache2/sites-enabled
    ssh_config_file_path: /etc/ssh/
  tasks:
    # - name: include file
    #   ansible.builtin.include_vars: 
    #     /home/hung/Desktop/DOAN/mysql_credential.yml

    # - name: include file
    #   ansible.builtin.include_vars: 
    #     /home/ansible/Desktop/DOAN/mysql_credential.yml
 
    - name: Check if pam_pwquality.so exists
      stat:
        path: /lib/*/security/pam_pwquality.so  # Update the path if needed
      register: pwquality_file

    - name: Install pam_pwquality package if not present
      ansible.builtin.apt:  # Use 'ansible.builtin.apt' if you are using a Debian-based system
        name: libpam-pwquality
        state: present
      when: pwquality_file.stat.exists == false

    - name: Print a message if pam_pwquality.so was installed
      debug:
        msg: "pam_pwquality.so has been installed."
      when: pwquality_file.stat.exists == false



