---
- name: test
  hosts: openstack_controller
  # become: yes
  vars:

  
    keystone_path: /etc/keystone
    horizon_path: /etc/openstack-dashboard/local_settings.py
    nova_path: /etc/nova
    cinder_path: /etc/cinder
    manila_path: /etc/manila
    neutron_path: /etc/neutron
    cron_tab_path: /etc
    cron_files_name: [cron.daily, cron.hourly, cron.monthly, cron.weekly, crontab]
    site_default_path: /etc/apache2/sites-enabled
    ssh_config_file_path: /etc/ssh/
    disable_modules: [status, proxy]
    DocumentRoot: /var/www/
    insecure_packages: [isc-dhcp-server, slapd, ldap-utils, bind9] 
    critical_file: [passwd, shadow, group, passwd-, shadow-,gshadow, group-,shells, opasswd]
    keystone_config_dest: /etc/keystone/keystone.conf
  tasks:
    # - name: include file
    #   ansible.builtin.include_vars: 
    #     /home/ansible/Desktop/DOAN/mysql_credential.yml
 
    # - name: add max_request_body_size
    #   ansible.builtin.blockinfile:
    #     path: "{{ keystone_config_dest }}"
    #     block: |
    #       [oslo_middleware]
    #       max_request_body_size = 114688
    #   become: true

    # - name: set insecure_debug = false
    #   ansible.builtin.lineinfile:
    #     path: "{{ keystone_config_dest }}"
    #     line: insecure_debug = false
    #     insertafter: '^\[DEFAULT\]'
    #   become: true

    # - name: disable admin_token  from the [default] section
    #   community.general.ini_file:
    #     path: "{{ keystone_config_dest }}"
    #     section: DEFAULT
    #     option: admin_token
    #     state: absent
    #   become: true

    # - name: disable admin_token  from the [default] section
    #   community.general.ini_file:
    #     path: "{{ keystone_config_dest }}"
    #     section: DEFAULT
    #     option: insecure_debug
    #     state: absent
    #   become: true
    
    # - name: set provider token = fernet
    #   ansible.builtin.lineinfile:
    #     path: "{{ keystone_config_dest }}"
    #     regexp: "provider"
    #     line: provider = fernet
    #   become: true



