---
# tasks file for ApacheHTTP_secure
- name: enable https for default site (testing)
  ansible.builtin.template:
    src: "/home/hung/Desktop/DOAN/ApacheHTTP_secure/templates/000-default.conf.j2"
    dest: "{{ site_default_path/000-default.conf }}"
  become: yes