---    
###task 1: this task include "/tmp, /var, /var/tmp" section for config using fstab file
- name: task 1 - Separate partition (/tmp, /var, /var/tmp... using fstab)
  ansible.builtin.template:
    src: "{{ new_fstab_path }}"
    dest: "{{ origin_fstab_path }}/fstab"
    mode: 0644
  become: true
  notify: reload-deamon
  tags: task1

##if system not mounted before, run "mount" command, else run "mount -o remount" command
# - name: remount
#   ansible.builtin.command: 
#     mount /tmp
#   become: true

##remount /tmp, /var, /var/tmp, /var/log, /var/log/audit, /home
- name: remount
  ansible.builtin.command: 
    mount -o remount /tmp #/var/tmp; /var/log; /var/log/audit; /home
  become: true

- name: check result
  ansible.builtin.raw:
    "findmnt -nk /tmp && findmnt -nk /var && findmnt -kn /var/tmp && findmnt -kn /var/log 
    && findmnt -kn /home && findmnt -kn /dev/shm"
  register: mount_output
  
- name: display output
  ansible.builtin.debug:
    var: mount_output.stdout_lines

##reconf permission bootloader config
# chown root:root /boot/grub/grub.cfg
# chmod u-x,go-rwx /boot/grub/grub.cfg: 600
- name: task 2 - reconfig permission of grub.cfg
  ansible.builtin.file:
    path: "{{ boot_loader_path }}"
    owner: root
    group: root
    mode: 0600
  become: true

##process hardening
- name: task 3 - Ensure prelink is not installed
  ansible.builtin.apt:
    name:
      - prelink
    state: absent
    purge: true
  become: true

- name: task4 - config ASLR, ptrace_scope
  ansible.builtin.template:
    src: "{{ sysctl_src }}"
    dest: "{{ sysctl_dest }}/sysctl.conf"
    mode: 0644
  become: true

##disable apport.service (enabled=0)
- name: task 5 - Ensure Automatic Error Reporting is not enabled
  ansible.builtin.template:
    src: "{{ apport_src }}"
    dest: "{{ apport_dest }}/apport"
    mode: 0644
  become: true

# systemctl stop apport.service
# systemctl --now disable apport.service
- name: stop apport service 
  ansible.builtin.systemd:
    name: apport.service
    state: stopped
    enabled: false
  become: true
  notify: reload-deamon


##you also can just remove this service 
# - name: remove apport service
#   ansible.builtin.apt:
#     name: apport
#     state: absent
#     purge: true
#   become: true

##Mandatory access control
##AppArmor provides a Mandatory Access Control (MAC)
- name: task 6 - install AppArmor
  ansible.builtin.apt:
    name:
      - apparmor
      - apparmor-utils
    state: latest
  become: true

#GRUB_CMDLINE_LINUX="apparmor=1 security=apparmor"
- name: config AppArmor
  ansible.builtin.template:
    src: "{{ grub_src }}"
    dest: "{{ grb_dest }}/grub"
    mode: 0644
  become: true
  notify: update-grub

## apparmor_status | grep profiles
## apparmor_status | grep processes
##set enforce mode or complain mode
##aa-enforce /etc/apparmor.d/*
#or
##aa-complain /etc/apparmor.d/*
- name: set enforce mode
  ansible.builtin.raw: aa-enforce /etc/apparmor.d/*
  become: true

- name: set complain mode
  ansible.builtin.raw: aa-complain /etc/apparmor.d/*
  become: true

  
    


