---
# handlers file for os_Secure
- name: reload-deamon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

#update grub
- name: update-grub
  ansible.builtin.command:
    update-grub
  become: true

#systemd-timesyncd.service is disabled
- name: disable-systemd-timesyncd.service
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    state: stopped
    enabled: false
  become: true

#unintall chrony
- name: uninstall-chrony
  ansible.builtin.apt:
    name: chrony
    state: absent
    purge: true
  become: true

#unintall NTP 
- name: uninstall-NTP
  ansible.builtin.apt:
    name: ntp 
    state: absent
    purge: true
  become: true

#start ufw
- name: start-ufw
  ansible.builtin.systemd:
    name: ufw.service
    state: started
  become: true

#uninstall ufw
- name: uninstall-ufw
  ansible.builtin.apt:
    name: ufw.service
    state: absent
    purge: true
  become: true

#unintall nftables
- name: uninstall-nftables
  ansible.builtin.apt:
    name: nftables
    state: absent
    purge: true
  become: true

- name: uninstall-iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    state: absent
  become: true