---
# handlers file for os_Secure
- name: reload-deamon
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

#update grub
- name: update-grub
  ansible.builtin.command:
    update-grub
  become: true